config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :workshops do
    post :email_all, on: :member
    resources :registrations
  end

  devise_for :users
  devise_for :admins

  resources :users, only: [:index]

  get 'user/questionaire', :to => 'questionaires#show'

  root 'static_pages#home'

  get '/class', :to => 'static_pages#about_class'
  get '/contact', :to => 'static_pages#contact'
  get '/resources', :to => 'static_pages#resources'
  post '/email_message', :to => 'static_pages#email_message'

end

app/models/workshop.rb
# subject: string
# time: datetime
# limit: integer

class Workshop < ActiveRecord::Base
  belongs_to :location
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations

  scope :sorted_by_time, -> { order(time: :asc) }
  scope :upcoming, -> { where("time > ?", DateTime.now).sorted_by_time }

  validates_presence_of :subject, :time, :limit, :location, :price, :plus_one_price
  validates_numericality_of :price

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :register, :update, :destroy, :email_all]
  before_action :admin_only, only: [:new, :edit, :create, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]


  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = current_user && current_user.admin? ? Workshop.sorted_by_time : Workshop.upcoming
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email_all
    @recipients = @workshop.users.all.map { |u| u.email }
    @subject = params['email_all']['subject']
    @body = params['email_all']['body']

    BulkMailer.send_bulk(@recipients, @subject, @body).deliver

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def register_user(user)
      if @workshop.users.count != @workshop.limit
        @workshop.users << user
      end
    end

    def workshop_params
      validated_params.require(:workshop).permit(:location_id, :subject, :time, :limit, :price, :plus_one_price)
    end

    def validated_params
      price_param = params['workshop']['price']
      price_param.nil? ? params : params.merge('price' => price_param.split('.').join)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
  def spots_left(workshop)
    workshop.limit - workshop.users.count
  end

  def date_format(datetime)
    datetime.strftime("%b %d, %Y")
  end

  def time_format(date_time)
    date_time.strftime("%l:%M %p")
  end

  def user_responses(user, workshop)
    Registration.find_by(user_id: user, workshop_id: workshop.id).questionaire
  end

  def baby_age(user, workshop)
    distance_of_time_in_words(workshop.time, user_responses(user, workshop).baby_dob, accumulate_on: :months, only: :months)
  end

  def price_in_dollars(price_in_cents)
    number_to_currency(price_in_cents / 100)
  end
end

app/views/workshops/_form.html.erb
<div class="row form-row">
  <div class="col-lg-4">

    <%= form_for(@workshop) do |f| %>
      <% if @workshop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

          <ul>
          <% @workshop.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group form-inline">
        <%= f.label :location %>
        <!-- <%= select_tag(:location, options_for_select(Location.all.map { |l| l.name }), class: 'form-control') %>  -->
        <%= f.collection_select(:location_id, Location.all, :id, :name, {}, {class: 'form-control'} )  %>
        <%= link_to("Add New", new_location_path) %>
      </div>

      <div class="field form-group">
        <%= f.label :subject %><br>
        <%= f.text_field :subject, class: 'form-control' %>
      </div>
      <div class="field form-group form-inline">
        <%= f.label :time %><br>
        <%= f.datetime_select :time, {}, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :limit %><br>
        <%= f.number_field :limit, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :price, 'Price (in cents)' %><br>
        <%= f.number_field :price, step: :any, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :plus_one_price, 'Plus One Price (in cents)' %>
        <%= f.number_field :plus_one_price , step: :any, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit(class: 'btn btn-default')%>
      </div>
    <% end %>
  </div>
</div>

app/views/workshops/edit.html.erb
<header class="section-header">
  <h1>Editing Workshop</h1>
</header>

<%= render 'form' %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/email_all.js.erb
$('#emailModal').modal('hide');
$('nav.navbar.navbar-default').append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p>Message Sent.</p></div>');

app/views/workshops/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="col-header">
      <h1>Upcoming Workshops</h1>
      <p>Registration Required <i>One Week Prior</i> to Workshop Date</p>
    </div>
    <div class="col-content">
      <div>
        <table class="table datatable table-responsive">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <% if admin_present? %>
                <th></th>
                <th></th>
                <th></th>
              <% else %>
                <th></th>
              <% end %>

            </tr>
          </thead>

          <tbody>
            <% @workshops.each do |workshop| %>
              <tr>
                <td><%= date_format(workshop.time) %></td>
                <td><%= time_format(workshop.time) %></td>
                <td>
                  <%= link_to(workshop.location.name, '#',
                  data: { toggle: "modal", target: "#locationModal", name: workshop.location.name, address: workshop.location.address}) %>
                </td>
                <td><%= price_in_dollars(workshop.price) %></td>
                <% if workshop.users.include?(current_user) %>
                  <td>Registered</td>
                <% else %>
                  <td><%= link_to("Register", new_workshop_registration_path(workshop), class: 'btn btn-default', data: { turbolinks: false }) unless admin_present? %></td>
                <% end %>
                <%if admin_present?  %>
                  <td><%= link_to 'Show', workshop, class: 'btn btn-default' %></td>
                  <td><%= link_to 'Edit', edit_workshop_path(workshop), class: 'btn btn-default' %></td>
                  <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <br>

      <% if admin_present? %>
        <%= link_to 'New Workshop', new_workshop_path %>
      <% end %>
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <div class="col-inner" id="disclaimer">
            <p>*Babies-in-arms are welcome, but do require registration of an additional care provider to minimize distractions.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="locationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modalTitle"></h4>
      </div>
      <div class="modal-body">
        <p id="modalText"></p>
      </div>
    </div>
  </div>
</div>

app/views/workshops/new.html.erb
<h1>New Workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <h1>Workshop Information</h1>
    <br>
    <p>
      <strong>Location:</strong>
      <%= @workshop.location.name %>
    </p>


    <p>
      <strong>Subject:</strong>
      <%= @workshop.subject %>
    </p>

    <p>
      <strong>Time:</strong>
      <%= @workshop.time %>
    </p>

    <p>
      <strong>Limit:</strong>
      <%= @workshop.limit %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= price_in_dollars(@workshop.price)  %>
    </p>

  </div>
  <div class="col-lg-8">
    <% if admin_present? %>
      <h1><%= pluralize(@workshop.users.length, 'Registered User' )%> </h1>

      <button type="button" class="btn btn-default" data-toggle="modal" data-target="#emailModal">Email All</button>

      <table class="table">
        <thead>
          <th>Name</th>
          <th>Baby's Name</th>
          <th>Email</th>
          <th>Baby's Age</th>
          <th>Plus One?</th>
          <th></th>
        </thead>
        <% User.sorted_by_baby_dob(@workshop).each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.registrations.find_by(workshop_id: @workshop).questionaire.baby_name %></td>
            <td><%= user.email %></td>
            <td><%= baby_age(user, @workshop)  %></td>
            <td><%= user.registrations.find_by(workshop_id: @workshop).plus_one  %></td>
            <td><%= link_to("View Responses",
                             user_questionaire_path(workshop_id: @workshop.id, user_id: user.id),
                             class: 'btn btn-default' ) %></a></td>          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <% if admin_present? %>
        <%= link_to 'Edit', edit_workshop_path(@workshop) %> |
      <% end %>
        <%= link_to 'Back', workshops_path %>
    </div>
  </div>
</div>

<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">EMAIL CLASS</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for :email_all, url: email_all_workshop_path(@workshop), remote: true do |form| %>
              <div class="field form-group">
                <%= form.label "Subject"  %>
                <%= form.text_field :subject, class: 'form-control' %>
              </div>

              <div class="field form-group">
                <%= form.label "Body"  %>
                <%= form.text_area :body, class: 'form-control' %>
              </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit "Send", class: 'btn btn-primary' %>
        <% end  %>
      </div>
    </div>
  </div>
</div>