config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :workshops do
    post :email_all, on: :member
    resources :registrations
  end

  devise_for :users
  devise_for :admins

  resources :users, only: [:index]

  get 'user/questionaire', :to => 'questionaires#show'

  root 'static_pages#home'

  get '/class', :to => 'static_pages#about_class'
  get '/contact', :to => 'static_pages#contact'
  get '/resources', :to => 'static_pages#resources'
  post '/email_message', :to => 'static_pages#email_message'

end

app/models/questionaire.rb
class Questionaire < ActiveRecord::Base
  belongs_to :registration
  validates :baby_name, :baby_dob, :nap_location,
            :night_location, :desired_sleep_location,
            :nap_routine, :night_routine, :naps_per_day,
            :bedtime, :sleep_obstacle, :nightwakings,
            :sleep_goal, :referred_by, presence: true
end

app/controllers/questionaires_controller.rb
class QuestionairesController < ApplicationController
  before_action :admin_only


  def show
    @questionaire = Registration.find_by(user_id: params[:user_id],
                                         workshop_id: params[:workshop_id]).questionaire
  end

  # private
  #   def set_questionaire
  #     @questionaire = Questionaire.find(params[:id])
  #   end

  #   def questionaire_params
  #     params.require(:questionaire).permit(:baby_name, :baby_dob, :nap_location, :night_location, :desired_sleep_location, :nap_routine, :night_routine, :naps_per_day, :bedtime, :sleep_obstacle, :nightwakings, :sleep_goal, :referred_by)
  #   end
end

app/helpers/questionaires_helper.rb
module QuestionairesHelper
end

app/views/questionaires/_form.html.erb
<%= form_for(@questionaire) do |f| %>
  <% if @questionaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionaire.errors.count, "error") %> prohibited this questionaire from being saved:</h2>

      <ul>
      <% @questionaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :baby_name %><br>
    <%= f.text_area :baby_name %>
  </div>
  <div class="field">
    <%= f.label :baby_dob %><br>
    <%= f.datetime_select :baby_dob %>
  </div>
  <div class="field">
    <%= f.label :nap_location %><br>
    <%= f.text_field :nap_location %>
  </div>
  <div class="field">
    <%= f.label :night_location %><br>
    <%= f.text_field :night_location %>
  </div>
  <div class="field">
    <%= f.label :desired_sleep_location %><br>
    <%= f.text_field :desired_sleep_location %>
  </div>
  <div class="field">
    <%= f.label :nap_routine %><br>
    <%= f.text_field :nap_routine %>
  </div>
  <div class="field">
    <%= f.label :night_routine %><br>
    <%= f.text_field :night_routine %>
  </div>
  <div class="field">
    <%= f.label :naps_per_day %><br>
    <%= f.number_field :naps_per_day %>
  </div>
  <div class="field">
    <%= f.label :bedtime %><br>
    <%= f.time_select :bedtime %>
  </div>
  <div class="field">
    <%= f.label :sleep_obstacle %><br>
    <%= f.text_field :sleep_obstacle %>
  </div>
  <div class="field">
    <%= f.label :nightwakings %><br>
    <%= f.number_field :nightwakings %>
  </div>
  <div class="field">
    <%= f.label :sleep_goal %><br>
    <%= f.text_field :sleep_goal %>
  </div>
  <div class="field">
    <%= f.label :referred_by %><br>
    <%= f.text_field :referred_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionaires/edit.html.erb
<h1>Editing Questionaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionaire %> |
<%= link_to 'Back', questionaires_path %>

app/views/questionaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questionaires</h1>

<table>
  <thead>
    <tr>
      <th>Baby name</th>
      <th>Baby dob</th>
      <th>Nap location</th>
      <th>Night location</th>
      <th>Desired sleep location</th>
      <th>Nap routine</th>
      <th>Night routine</th>
      <th>Naps per day</th>
      <th>Bedtime</th>
      <th>Sleep obstacle</th>
      <th>Nightwakings</th>
      <th>Sleep goal</th>
      <th>Referred by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionaires.each do |questionaire| %>
      <tr>
        <td><%= questionaire.baby_name %></td>
        <td><%= questionaire.baby_dob %></td>
        <td><%= questionaire.nap_location %></td>
        <td><%= questionaire.night_location %></td>
        <td><%= questionaire.desired_sleep_location %></td>
        <td><%= questionaire.nap_routine %></td>
        <td><%= questionaire.night_routine %></td>
        <td><%= questionaire.naps_per_day %></td>
        <td><%= questionaire.bedtime %></td>
        <td><%= questionaire.sleep_obstacle %></td>
        <td><%= questionaire.nightwakings %></td>
        <td><%= questionaire.sleep_goal %></td>
        <td><%= questionaire.referred_by %></td>
        <td><%= link_to 'Show', questionaire %></td>
        <td><%= link_to 'Edit', edit_questionaire_path(questionaire) %></td>
        <td><%= link_to 'Destroy', questionaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionaire', new_questionaire_path %>

app/views/questionaires/new.html.erb
<h1>New Questionaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionaires_path %>

app/views/questionaires/show.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <h3><%= @questionaire.registration.user.name %></h3>

    <table class="table table-bordered">
      <thead>
        <th></th>
        <th></th>
      </thead>
        <% attributes = @questionaire.attributes.except('id', 'registration_id', 'created_at', 'updated_at') %>
        <% attributes.each do |key, value| %>
          <tr>
            <td><strong><%= key %>:</strong></td>
            <% if key == 'baby_dob' %>
              <td><%= date_format(value) %></td>
            <% elsif key == 'bedtime' %>
              <td><%= time_format(value) %></td>
            <% else %>
              <td><%= value %></td>
            <% end %>
          </tr>
        <% end %>
    </table>

    <%= link_to 'Back', workshops_path %>

  </div>
</div>