config/routes.rb
Rails.application.routes.draw do
  resources :locations

  resources :workshops do
    post :email_all, on: :member
    resources :registrations
  end

  devise_for :users
  devise_for :admins

  resources :users, only: [:index]

  get 'user/questionaire', :to => 'questionaires#show'

  root 'static_pages#home'

  get '/class', :to => 'static_pages#about_class'
  get '/contact', :to => 'static_pages#contact'
  get '/resources', :to => 'static_pages#resources'
  post '/email_message', :to => 'static_pages#email_message'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweet Slumber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
  <div class="body-wrapper">
    <div class="container-fluid full-width" id="header-container">
      <header class="brand">
        <h1>Sweet Slumber</h1>
      </header>
      <nav class="navbar navbar-default">
        <div class="container-fluid full-width navbar-inner">
          <div class="navbar-header">
            <h2>
            <%= link_to("Sweet Slumber", root_url, class: 'navbar-brand' ) %>
            </h2>
            <div class="collapse-button">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav centered">
              <li><%= link_to("Home", root_url) %></li>
              <li><%= link_to("About", class_path) %></li>
              <li><%= link_to("Schedule", workshops_url) %></li>

              <% if registered_user? %>
                <li><%= link_to("Resources", resources_path) %></li>
              <% elsif admin_present? %>
                <li><%= link_to("Users", users_path) %></li>
              <% end %>

              <li><%= link_to("Contact", contact_path) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in?  %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret" ></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to("Edit Profile", edit_user_registration_path) %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>

            <% else %>
              <li><%= link_to("Login", new_user_session_path) %></li>
            <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <% if notice %>
        <div class="alert alert-success alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <p><%= alert %></p>
        </div>
      <% end %>

    </div>

    <div class="container-fluid" id="main-content">
      <div class="container" id="content">
        <%= yield %>
      </div>

      <div class="row footer">
        <div class="col-lg-6 col-lg-offset-3">
          <div class="col-inner" id="quote">
            <i>. . .</i>
            <header>
              <h2>
                Teaching your baby how to sleep gives them a foundation for self-care.
              </h2>
            </header>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>